config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :outputs
  resources :price_data

  root to: 'outputs#welcome', as: :welcome

  resources :users, only: [:new, :show, :index, :create]
  post '/outputs/create_image', to: 'outputs#create_image'
  get '/image_test', to: 'outputs#image_test'
  get '/login', to: 'sessions#new', as: 'login'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy', as: 'logout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Build Calculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<html>
  <head>
    <title>Build Calculator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/"><%= image_tag ("buildable_logo_white.png") %></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Create Estimate", new_output_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "View Old Estimates", outputs_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Add Price Data", new_price_datum_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "View Database", price_data_path, class: "nav-link" %>
      </li>
      <% if session[:user_id] == nil %>
      <li class="nav-item">
      <%= link_to "Login", login_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
      <%= link_to "Logged in as: #{User.find_by(id: session[:user_id]).username}" , :welcome, class: "nav-link" %>
      </li>
      <li class="nav-item">
      <%= link_to "Log Out", '/logout', method: :delete, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>